Style/FrozenStringLiteralComment:
  Exclude:
    - 'features/step_definitions/user_steps.rb'
    - 'features/support/env.rb'

Layout/LineLength:
  Max: 130
  Exclude:
    - 'features/support/env.rb'

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 40
