version: '3.4'

services:
  verify-tests:
    build: .

  selenium-hub:
    image: selenium/hub:4.0.0
    ports:
      - "4444:4444"

  firefoxnode:
    image: selenium/node-firefox:88.0
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
    ports:
      - "5555"
    depends_on:
      - selenium-hub
