local:
  frontend: http://localhost:50300
  test-rp: http://localhost:50130/test-rp
  idps:
    Stub Country: http://localhost:50140/eidas/stub-country/login

docker-local:
  frontend: http://frontend
  test-rp: http://test-rp/test-rp
  idps:
    Stub Country: http://stub-idp/eidas/stub-country/login

joint:
  frontend: https://www.joint.signin.service.gov.uk
  test-rp: https://test-rp-stub-joint.ida.digital.cabinet-office.gov.uk/test-rp
  idps:
    Stub Country: https://ida-stub-idp-joint.cloudapps.digital/eidas/stub-country/login
